### calling root api with get method
GET  http://localhost:8000/

### calling root api with get method
GET  http://localhost:8000/api/v1/task

### calling root api with post method
POST  http://localhost:8000/api/v1/task